const thanksMessage = [
  '素晴らしい掃除のおかげで快適です．ありがとうございます！',
  '綺麗にしてくれて心から感謝します．いつもありがとう！',
  '掃除の努力に感謝’！おかげで気持ちよく過ごせます',
  'あなたの掃除のおかげで清潔な環境が保たれています．’感謝！',
  '丁寧な掃除，本当にありがとう！’いつも感謝しています',
  '掃除のおかげで集中して研究ができます！’ありがとう！',
  '綺麗な環境を作ってくれて感動です！ありがとう',
  'いつも清潔にしてくれて本当に助かっています．ありがとうございます',
  '感谢你出色的清洁工作，让环境舒适！',
  '打扫得这么干净，真心感谢你！',
  '感谢你辛勤的清洁工作，让人感到愉快。',
  '你的清洁工作使环境保持整洁。非常感谢！',
  '谢谢你的细心打扫，一直感激不尽！',
  '因为你的清洁工作，我能专心研究！谢谢你！',
  '你创造了一个干净的环境，真的很感动，谢谢！',
  '你一直保持环境清洁，真的帮了大忙，谢谢！',
  '¡Gracias por tu excelente limpieza, el ambiente es muy cómodo!',
  '¡De corazón, gracias por mantener todo limpio siempre!',
  '¡Agradezco tu esfuerzo en la limpieza, es un placer estar aquí!',
  '¡Gracias a tu limpieza, el ambiente se mantiene impecable!',
  '¡Gracias de verdad por tu minuciosa limpieza, siempre agradecido!',
  '¡Gracias a tu limpieza, puedo concentrarme en mi investigación!',
  '¡Es emocionante tener un ambiente tan limpio, gracias!',
  '¡Gracias de verdad por mantener todo tan limpio, es de gran ayuda!',
  'Thanks to your amazing cleaning, the environment is very comfortable!',
  'From the bottom of my heart, thank you for always keeping things clean!',
  'Appreciate your cleaning efforts, it makes the space enjoyable!',
  'Thanks to your cleaning, the environment remains spotless. Grateful!',
  'Truly thankful for your meticulous cleaning, always appreciated!',
  'Because of your cleaning, I can concentrate on my research. Thank you!',
  'It’s inspiring to have such a clean environment, thank you!',
  'Your constant cleaning really helps a lot, thank you so much!'
];

module.exports = thanksMessage;